-- No-op: this migration previously duplicated the same function body later canonicalized in
-- 20260322120000_normalize_round_robin_tiers_generator_declare_block.sql.
-- Kept intentionally to preserve migration ordering without redefinition drift.
